name: build

on:
  workflow_dispatch:
    inputs:
      runs-on:
        default: macos-latest
        description: 'The OS to run the build on'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: tpoechtrager/osxcross
          path: osxcross

      - name: Packaging the SDK
        working-directory: ./osxcross
        run: |
          ./tools/gen_sdk_package_tools.sh
          mv *.tar.* tarballs/
          mv *.pkg tarballs/ || true

      - name: Upload SDK tarballs to Rolling Release
        run: gh release upload rolling osxcross/tarballs/* -R ${{github.repository}} --clobber
