name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-26
          - macos-15
          - macos-14
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: tpoechtrager/osxcross
          path: osxcross

      - name: Packaging the SDK
        working-directory: ./osxcross
        run: |
          ./tools/gen_sdk_package_tools.sh
          mv *.tar.* tarballs/
          mv *.pkg tarballs/ || true

      - name: Upload SDK tarballs to Rolling Release
        run: gh release upload rolling osxcross/tarballs/* -R ${{github.repository}} --clobber
