name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-26
          - macos-15
          - macos-14
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: tpoechtrager/osxcross
          path: osxcross

      - name: Packaging the SDK
        run: ./gen_sdk_packages.sh

      - name: Upload SDK tarballs to "${{ matrix.os }}" Release
        run: gh release upload "${{ matrix.os }}" osxcross/tarballs/* -R ${{github.repository}} --clobber
