name: build

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'Select the macOS version to run the job on'
        required: false
        default: 'macos-26'
        type: choice
        options:
          - macos-26
          - macos-15
          - macos-14

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: tpoechtrager/osxcross
          path: osxcross

      - name: Packaging the SDK
        run: ./gen_sdk_packages.sh

      - name: Upload SDK tarballs to Rolling Release
        run: gh release upload rolling osxcross/tarballs/* -R ${{github.repository}} --clobber
